#server:
#  port: 0 # 사용가능한 포트번호 임의로 할당해달라는 뜻 (0번 포트 아님!)
#  
#spring:
#  application:
#    name: member-service
#    
#    
#  h2: #h2데이터베이스 설정(어플리케이션에 내장->받아서 사용)
#    console:
#      enabled: true #브라우저에서 콘솔 보기 허용
#      settings:
#        web-allow-others: true
#      path: /h2-console
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true        
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#        
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    
#  client:
#    register-with-eureka: true #유레카 서버에 등록
#    fetch-registry: true #주기적으로 다른 인스턴스의 데이터 업데이트 허용
#    service-url:
#      defaultZone: http://localhost:8761/eureka #주소: 유레카서버의 포트번호 사용
#      
#      
#   
server:
  port: 0

  # port 번호를 지정하지 않고 사용할 수 있는 port 번호를 임의로 할당하라는 의미. 
  # (0번 port를 사용하겠다는 것이 아니다.)
  
spring:
  application:
    name: member-service
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
        

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usinsa_v2?serverTimezone=Asia/Seoul&characterEncoding=utf-8
    username: tj705
    password: tj705
      
      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # 유레가 서버에 등록
    fetch-registry: true # 주기적으로 다른 인스턴스의 데이터를 받아와 갱신
    service-url:
      defaultZone: http://localhost:8761/eureka # 유레가 커서의 주소 정보 
      
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh